-- ============================================================
-- SkillSwap - Indexes
-- ============================================================

-- USERS
CREATE INDEX IDX_USERS_STATUS
ON USERS (STATUS);

CREATE INDEX IDX_USERS_DEPARTMENT
ON USERS (DEPARTMENT_ID);

-- SKILLS
CREATE INDEX IDX_SKILLS_NAME
ON SKILLS (SKILL_NAME);

CREATE INDEX IDX_SKILLS_CATEGORY
ON SKILLS (CATEGORY_ID);

-- OFFERS
CREATE INDEX IDX_OFFERS_USER
ON OFFERS (USER_ID);

CREATE INDEX IDX_OFFERS_SKILL
ON OFFERS (SKILL_ID);

-- REQUESTS
CREATE INDEX IDX_REQUESTS_USER
ON REQUESTS (USER_ID);

CREATE INDEX IDX_REQUESTS_SKILL
ON REQUESTS (SKILL_ID);

CREATE INDEX IDX_REQUESTS_STATUS
ON REQUESTS (STATUS);

CREATE INDEX IDX_REQUESTS_OFFER
ON REQUESTS (OFFER_ID);

-- SESSIONS
CREATE INDEX IDX_SESSIONS_STATUS
ON SESSIONS (STATUS);

CREATE INDEX IDX_SESSIONS_OFFER
ON SESSIONS (OFFER_ID);

-- MESSAGES
CREATE INDEX IDX_MESSAGES_SESSION
ON MESSAGES (SESSION_ID);

CREATE INDEX IDX_MESSAGES_SENDER
ON MESSAGES (SENDER_ID);

-- NOTIFICATIONS
CREATE INDEX IDX_NOTIFICATIONS_USER
ON NOTIFICATIONS (TO_USER_ID);

CREATE INDEX IDX_NOTIFICATIONS_READ
ON NOTIFICATIONS (IS_READ);

CREATE INDEX IDX_NOTIFICATIONS_TYPE
ON NOTIFICATIONS (NOTIFICATION_TYPE);

-- ENDORSEMENTS
CREATE INDEX IDX_ENDORSEMENTS_USER
ON ENDORSEMENTS (ENDORSED_USER_ID);