-- ============================================================
-- SkillSwap - Final Oracle Database Schema
-- ============================================================

-- ============================================================
-- DEPARTMENTS
-- ============================================================
CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
FACULTY         VARCHAR2(100) NOT NULL,


CONSTRAINT UQ_DEPARTMENTS_NAME
    UNIQUE (DEPARTMENT_NAME)


);

-- ============================================================
-- SKILL CATEGORIES
-- ============================================================
CREATE TABLE SKILL_CATEGORIES (
CATEGORY_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
CATEGORY_NAME  VARCHAR2(100) NOT NULL,
DEPARTMENT_ID  NUMBER NOT NULL,


CONSTRAINT FK_SKILL_CATEGORIES_DEPT
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENTS (DEPARTMENT_ID),

CONSTRAINT UQ_SKILL_CATEGORIES_NAME
    UNIQUE (DEPARTMENT_ID, CATEGORY_NAME)


);

-- ============================================================
-- SKILLS
-- ============================================================
CREATE TABLE SKILLS (
SKILL_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
SKILL_NAME    VARCHAR2(100) NOT NULL,
CATEGORY_ID   NUMBER NOT NULL,


CONSTRAINT FK_SKILLS_CATEGORY
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES SKILL_CATEGORIES (CATEGORY_ID),

CONSTRAINT UQ_SKILLS_NAME
    UNIQUE (CATEGORY_ID, SKILL_NAME)


);

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE USERS (
USER_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
DEPARTMENT_ID  NUMBER NOT NULL,


NAME           VARCHAR2(200) NOT NULL,
BATCH          NUMBER(4) NOT NULL,

EMAIL          VARCHAR2(255) NOT NULL,
PHONE          VARCHAR2(20),

PASSWORD_HASH  VARCHAR2(255) NOT NULL,

ROLE           VARCHAR2(10) DEFAULT 'STUDENT' NOT NULL,
STATUS         VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,

CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT FK_USERS_DEPT
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENTS (DEPARTMENT_ID),

CONSTRAINT UQ_USERS_EMAIL
    UNIQUE (EMAIL),

CONSTRAINT CHK_USERS_ROLE
    CHECK (ROLE IN ('ADMIN','STUDENT')),

CONSTRAINT CHK_USERS_STATUS
    CHECK (STATUS IN ('ACTIVE','INACTIVE'))


);

-- ============================================================
-- SKILL SUGGESTIONS
-- ============================================================
CREATE TABLE SKILL_SUGGESTIONS (
SUGGESTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


USER_ID       NUMBER NOT NULL,
SKILL_NAME    VARCHAR2(150) NOT NULL,
CATEGORY_ID   NUMBER,

STATUS        VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,

SUGGESTED_AT  DATE DEFAULT SYSDATE NOT NULL,
REVIEWED_AT   DATE,

CONSTRAINT FK_SUGGESTIONS_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT FK_SUGGESTIONS_CAT
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES SKILL_CATEGORIES (CATEGORY_ID),

CONSTRAINT CHK_SUGGESTIONS_STATUS
    CHECK (STATUS IN ('PENDING','APPROVED','REJECTED'))


);

-- ============================================================
-- OFFERS
-- ============================================================
CREATE TABLE OFFERS (
OFFER_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


USER_ID       NUMBER NOT NULL,
SKILL_ID      NUMBER NOT NULL,

SKILL_LEVEL   VARCHAR2(15) NOT NULL,
SESSION_MODE  VARCHAR2(10) NOT NULL,

CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT FK_OFFERS_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT FK_OFFERS_SKILL
    FOREIGN KEY (SKILL_ID)
    REFERENCES SKILLS (SKILL_ID),

CONSTRAINT UQ_OFFERS_USER_SKILL
    UNIQUE (USER_ID, SKILL_ID),

CONSTRAINT CHK_OFFERS_LEVEL
    CHECK (SKILL_LEVEL IN ('BEGINNER','INTERMEDIATE','EXPERT')),

CONSTRAINT CHK_OFFERS_MODE
    CHECK (SESSION_MODE IN ('ONLINE','IN_PERSON','BOTH'))


);

-- ============================================================
-- AVAILABILITY
-- ============================================================
CREATE TABLE AVAILABILITY (
AVAILABILITY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


OFFER_ID        NUMBER NOT NULL,

DAY_OF_WEEK     VARCHAR2(10) NOT NULL,
TIME_SLOT       VARCHAR2(10) NOT NULL,

CONSTRAINT FK_AVAILABILITY_OFFER
    FOREIGN KEY (OFFER_ID)
    REFERENCES OFFERS (OFFER_ID),

CONSTRAINT CHK_AVAIL_DAY
    CHECK (
        DAY_OF_WEEK IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    ),

CONSTRAINT CHK_AVAIL_TIME
    CHECK (
        TIME_SLOT IN (
            'MORNING',
            'AFTERNOON',
            'EVENING'
        )
    ),

CONSTRAINT UQ_AVAIL_DAY_TIME
    UNIQUE (OFFER_ID, DAY_OF_WEEK, TIME_SLOT)


);

-- ============================================================
-- REQUESTS
-- ============================================================
CREATE TABLE REQUESTS (
REQUEST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


USER_ID NUMBER NOT NULL,
SKILL_ID NUMBER NOT NULL,

OFFER_ID NUMBER NOT NULL,
SELECTED_AVAILABILITY_ID NUMBER NOT NULL,

URGENCY VARCHAR2(10) DEFAULT 'LOW' NOT NULL,

NOTE VARCHAR2(500),

REQUESTED_AT DATE DEFAULT SYSDATE NOT NULL,

STATUS VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,

CONSTRAINT FK_REQUESTS_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT FK_REQUESTS_SKILL
    FOREIGN KEY (SKILL_ID)
    REFERENCES SKILLS (SKILL_ID),

CONSTRAINT FK_REQUESTS_OFFER
    FOREIGN KEY (OFFER_ID)
    REFERENCES OFFERS (OFFER_ID),

CONSTRAINT FK_REQUESTS_AVAIL
    FOREIGN KEY (SELECTED_AVAILABILITY_ID)
    REFERENCES AVAILABILITY (AVAILABILITY_ID),

CONSTRAINT CHK_REQUESTS_URGENCY
    CHECK (URGENCY IN ('LOW','MEDIUM','HIGH')),

CONSTRAINT CHK_REQUESTS_STATUS
    CHECK (
        STATUS IN (
            'PENDING',
            'ACCEPTED',
            'REJECTED',
            'COMPLETED',
            'CANCELLED'
        )
    )


);

-- ============================================================
-- SESSIONS
-- ============================================================
CREATE TABLE SESSIONS (
SESSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


OFFER_ID NUMBER NOT NULL,
REQUEST_ID NUMBER NOT NULL,

SESSION_DATE DATE NOT NULL,
MEETING_DETAIL VARCHAR2(255),

STATUS VARCHAR2(10) DEFAULT 'SCHEDULED' NOT NULL,

REQUESTER_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
OFFERER_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,

COMPLETED_AT DATE,

CONSTRAINT FK_SESSIONS_OFFER
    FOREIGN KEY (OFFER_ID)
    REFERENCES OFFERS (OFFER_ID),

CONSTRAINT FK_SESSIONS_REQUEST
    FOREIGN KEY (REQUEST_ID)
    REFERENCES REQUESTS (REQUEST_ID),

CONSTRAINT UQ_SESSIONS_REQUEST
    UNIQUE (REQUEST_ID),

CONSTRAINT CHK_SESSIONS_STATUS
    CHECK (
        STATUS IN (
            'SCHEDULED',
            'COMPLETED',
            'CANCELLED'
        )
    )


);

-- ============================================================
-- FEEDBACK
-- ============================================================
CREATE TABLE FEEDBACK (
FEEDBACK_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


SESSION_ID NUMBER NOT NULL,

SCORE NUMBER(1) NOT NULL,

FEEDBACK_TEXT VARCHAR2(1000),

GIVEN_AT DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT FK_FEEDBACK_SESSION
    FOREIGN KEY (SESSION_ID)
    REFERENCES SESSIONS (SESSION_ID),

CONSTRAINT UQ_FEEDBACK_SESSION
    UNIQUE (SESSION_ID),

CONSTRAINT CHK_FEEDBACK_SCORE
    CHECK (SCORE BETWEEN 1 AND 5)


);

-- ============================================================
-- ENDORSEMENTS
-- ============================================================
CREATE TABLE ENDORSEMENTS (
ENDORSEMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


ENDORSED_USER_ID NUMBER NOT NULL,
ENDORSED_BY_ID NUMBER NOT NULL,
SKILL_ID NUMBER NOT NULL,

NOTE VARCHAR2(500),

GIVEN_AT DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT FK_ENDORSE_USER
    FOREIGN KEY (ENDORSED_USER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT FK_ENDORSE_BY
    FOREIGN KEY (ENDORSED_BY_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT FK_ENDORSE_SKILL
    FOREIGN KEY (SKILL_ID)
    REFERENCES SKILLS (SKILL_ID),

CONSTRAINT UQ_ENDORSEMENT
    UNIQUE (
        ENDORSED_USER_ID,
        ENDORSED_BY_ID,
        SKILL_ID
    )


);

-- ============================================================
-- MESSAGES
-- ============================================================
CREATE TABLE MESSAGES (
MESSAGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


SESSION_ID NUMBER NOT NULL,
SENDER_ID NUMBER NOT NULL,

CONTENT VARCHAR2(4000) NOT NULL,

SENT_AT DATE DEFAULT SYSDATE NOT NULL,

IS_READ NUMBER(1) DEFAULT 0 NOT NULL,

CONSTRAINT FK_MESSAGES_SESSION
    FOREIGN KEY (SESSION_ID)
    REFERENCES SESSIONS (SESSION_ID),

CONSTRAINT FK_MESSAGES_SENDER
    FOREIGN KEY (SENDER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT CHK_MESSAGES_READ
    CHECK (IS_READ IN (0,1))


);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
CREATE TABLE NOTIFICATIONS (
NOTIFICATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,


TO_USER_ID NUMBER NOT NULL,
FROM_USER_ID NUMBER,

NOTIFICATION_TYPE VARCHAR2(15) NOT NULL,

CONTENT VARCHAR2(1000) NOT NULL,

CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

IS_READ NUMBER(1) DEFAULT 0 NOT NULL,

CONSTRAINT FK_NOTIF_TO_USER
    FOREIGN KEY (TO_USER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT FK_NOTIF_FROM_USER
    FOREIGN KEY (FROM_USER_ID)
    REFERENCES USERS (USER_ID),

CONSTRAINT CHK_NOTIF_TYPE
    CHECK (
        NOTIFICATION_TYPE IN (
            'MATCH',
            'SESSION',
            'FEEDBACK',
            'ENDORSEMENT',
            'MESSAGE'
        )
    ),

CONSTRAINT CHK_NOTIF_IS_READ
    CHECK (IS_READ IN (0,1))


);
