--SELECT COUNT(*) FROM USERS;
--
--SELECT COUNT(*) FROM SKILLS;
--
--SELECT COUNT(*) FROM OFFERS;
--
--SELECT COUNT(*) FROM REQUESTS;
--
--SELECT COUNT(*) FROM SESSIONS;
--
--SELECT SYS_CONTEXT('USERENV', 'DB_NAME') FROM DUAL;
--
--SELECT SYS_CONTEXT('USERENV', 'SERVICE_NAME') FROM DUAL;

--DESC USERS;
--DESC OFFERS;
--DESC REQUESTS;
--DESC NOTIFICATIONS;

--SELECT EMAIL, PASSWORD_HASH
--FROM USERS
--WHERE ROWNUM <= 5;

--DESC SKILLS;
--DESC SKILL_CATEGORIES;
--DESC OFFERS;
--DESC DEPARTMENTS;

DESC REQUESTS;
DESC SESSIONS;
DESC NOTIFICATIONS;
DESC MESSAGES;
DESC FEEDBACK;