-- ============================================================
-- SkillSwap - Views
-- ============================================================

-- Top rated offerers (by average feedback score)
CREATE OR REPLACE VIEW VW_TOP_RATED_OFFERERS AS
SELECT U.USER_ID,
       U.NAME AS OFFERER_NAME,
       ROUND(AVG(F.SCORE), 2) AS AVG_SCORE,
       COUNT(F.FEEDBACK_ID) AS FEEDBACK_COUNT
FROM USERS U
JOIN OFFERS O
  ON U.USER_ID = O.USER_ID
JOIN REQUESTS R
  ON O.OFFER_ID = R.OFFER_ID
JOIN SESSIONS S
  ON R.REQUEST_ID = S.REQUEST_ID
JOIN FEEDBACK F
  ON S.SESSION_ID = F.SESSION_ID
GROUP BY U.USER_ID, U.NAME;

-- Most requested skills
CREATE OR REPLACE VIEW VW_MOST_REQUESTED_SKILLS AS
SELECT SK.SKILL_ID,
       SK.SKILL_NAME,
       COUNT(R.REQUEST_ID) AS REQUEST_COUNT
FROM SKILLS SK
JOIN REQUESTS R
  ON SK.SKILL_ID = R.SKILL_ID
GROUP BY SK.SKILL_ID, SK.SKILL_NAME;

-- Most offered skills
CREATE OR REPLACE VIEW VW_MOST_OFFERED_SKILLS AS
SELECT SK.SKILL_ID,
       SK.SKILL_NAME,
       COUNT(O.OFFER_ID) AS OFFER_COUNT
FROM SKILLS SK
JOIN OFFERS O
  ON SK.SKILL_ID = O.SKILL_ID
GROUP BY SK.SKILL_ID, SK.SKILL_NAME;

-- Active departments (count of active users per department)
CREATE OR REPLACE VIEW VW_ACTIVE_DEPARTMENTS AS
SELECT D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       COUNT(U.USER_ID) AS ACTIVE_USERS
FROM DEPARTMENTS D
JOIN USERS U
  ON D.DEPARTMENT_ID = U.DEPARTMENT_ID
WHERE U.STATUS = 'ACTIVE'
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;

-- Pending requests
CREATE OR REPLACE VIEW VW_PENDING_REQUESTS AS
SELECT R.REQUEST_ID,
       U.NAME AS REQUESTER_NAME,
       O.OFFER_ID,
       SK.SKILL_NAME,
       R.URGENCY,
       R.NOTE
FROM REQUESTS R
JOIN USERS U
  ON R.USER_ID = U.USER_ID
JOIN OFFERS O
  ON R.OFFER_ID = O.OFFER_ID
JOIN SKILLS SK
  ON R.SKILL_ID = SK.SKILL_ID
WHERE R.STATUS = 'PENDING';

-- Inactive users
CREATE OR REPLACE VIEW VW_INACTIVE_USERS AS
SELECT U.USER_ID,
       U.NAME AS USER_NAME,
       D.DEPARTMENT_NAME,
       U.EMAIL
FROM USERS U
JOIN DEPARTMENTS D
  ON U.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE U.STATUS = 'INACTIVE';